version: '3.4'

services:
  node:
    container_name: nexpws_node_1
    restart: always
    image: digichanges/nexp:1.0
    working_dir: /usr/app
    entrypoint: bash prod.build.sh
    volumes:
      - .:/usr/app:cached
    ports:
      - "8089:8089"
    networks:
      - nexpwsnet
